config/routes.rb
Rails.application.routes.draw do

  resources :tenants do
    resources :boards, only: [:index, :new, :create]

    resources :boards do
      collection do
        get :select_all
      end
    end 

    resources :members do
      collection do # invite_tenant_members POST /tenants/:tenant_id/members/invite(.:format) members#invite
        post :invite # Invite a member to the current tenant
        get :select_all
      end
    end
  end

  resources :boards, only: [:show, :edit, :update, :destroy]

  resources :boards, only: [:show] do
    resources :lists, only: [:index, :new, :create]  
  end

  # DEFINE ROUTES FOR :tasks, :lists, :sort  (:show, :edit, :update, :destroy)

  resources :lists, only: [:show] do
    resources :tasks, only: [:index, :new, :create]  
  end

  resources :lists, only: [:show, :edit, :update, :destroy] do
    member do # sort_list PUT /lists/:id/sort(.:format) lists#sort
      put :sort
      patch :update_name
    end
  end 

  resources :tasks, only: [:show, :edit, :update, :destroy] do
    member do # sort_task PUT /tasks/:id/sort(.:format) tasks#sort
      put :sort
    end
  end

  resources :tasks do
    resource :cover_image, only: [:destroy], module: :tasks
  end

# SEARCH TASKS
# get 'search_friend', to: 'users#search'



  # resources :tasks do
  #   member do # sort_task PUT /tasks/:id/sort(.:format) tasks#sort
  #     put :sort
  #   end
  # end


  # collection do - sort_lists 
  # member do - sort list


  # collection do - invite_tenant_members 
  # member do - invite_tenant_member


  # resources :blog_posts do
  #   resource :cover_image, only: [:destroy], module: :blog_posts
  # end

  # get "/tenants/:tenant_id/boards", to: "boards#index", as: "boards"
  #post "/tenants/:tenant_id/boards", to: "boards#create", as: "boards"

  # post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"

  # devise_for :users
  # devise_for :users, :controllers => { :invitations => 'invitations' }


    devise_for :users, controllers: {
      registrations: "users/registrations"
    }

  put 'boards/users/sidebar_position', to: "preferences#sidebar_position"
  # get 'boards/users/sidebar_position', to: "preferences#get"
  root 'static_pages#landing_page'
  get 'dashboard', to: 'static_pages#dashboard'

  get 'selected_board', to: 'tasks#selected_board'

  get 'selected_list', to: 'tasks#selected_list'

  # PDF
  get 'tasks/pdf/:id', to: 'tasks#pdf', as: 'task_pdf'
  
  get "download_pdf", to: "tasks#pdf_download"
  get "preview_pdf", to: "tasks#pdf_preview"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/list.rb
class List < ApplicationRecord
    validates :name, presence: true
    
    has_many :tasks, dependent: :destroy
    belongs_to :board

    # scope :sorted, -> { order(Arel.sql("created_at DESC NULLS FIRST")).order(updated_at: :desc) }
    # scope :sorted, -> { order(Arel.sql("row_order ASC NULLS FIRST")) }
    # scope :sorted, -> { order(Arel.sql("row_order ASC NULLS FIRST")).order(updated_at: :asc)  }

    include RankedModel
    ranks :row_order, with_same: :board_id
   
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy update_name ]

  include ActionView::RecordIdentifier # include dom_id method identifier

  # GET /lists or /lists.json
  def index
    # @lists = List.all
    @lists = List.where(board_id: params[:board_id]).rank(:row_order)
    # @lists = List.all
    # @lists = List.sorted
  end

  def sort
    @list = List.find(params[:id])
    respond_to do |format|
      if @list.update(row_order_position: params[:row_order_position])
        # debugger

        format.html {
          headers["www-Authenticate"] = root_url
          # head :unauthorized
          head :no_content
        }
        # format.turbo_stream{ head :no_content }
        # format.turbo_stream { render "users/new_friend", 
        #   locals: { friend: "", allowed: false,  flash_notice: "The friend #{params[:full_name]} #{params[:email]} is already trackt!" }
        # }
        @update_list = dom_id(@list, :sortable)
        # debugger
        #format.turbo_stream { render turbo_stream: turbo_stream.update(dom_id(@list, :sortable))}
        format.turbo_stream { render "update_list", 
          locals: { list: @list, update_list: @update_list  }
        }        
        # format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(@scan, :uploaded_image))}

      end
    end
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
    positions = []
    i = 0
    List.where(board_id: @list.board_id).rank(:row_order).each do |list|
      positions[i]=[list.row_order, i+1]
      i=i+1      
    end
    @positions = positions

    #debugger
  end

  # POST /lists or /lists.json
  def create
    # debugger
    @list = List.new(name: params[:name], board_id: params[:board_id])

    respond_to do |format|

      if @list.save

        
        @board = Board.find(@list.board_id)

        format.turbo_stream { render "lists/update_lists", 
          locals: { board: @board, list: @list, position: 0  }
        }
        
        # format.turbo_stream { render "prepend_list", 
        #   locals: { list: @list }
        # }

        format.html { redirect_to "/boards/#{@list.board_id}", notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_name
    
    # debugger

    last_list = List.find(params[:id])
    

    respond_to do |format| 
      if @list.update(list_params)


        @update_list = dom_id(@list, :sortable)
        # @board = Board.find(@list.board_id)

        # format.turbo_stream { render "update_lists", 
        #   locals: { board: @board, list: @list, position: pos_new }
        # }

        # format.turbo_stream { render "update_list", 
        #   locals: { list: @list, update_list: @update_list  }
        # }

        # format.html { redirect_to "/boards/#{@list.board_id}", notice: "List was successfully updated." }
        # format.json { render :show, status: :ok, location: @list }

        format.json { render json: { status: 'ok', name: @list.name } }
      else
        # format.turbo_stream { render "update_list", 
        #   locals: { list: @list, update_list: @update_list  }
        # }

        # format.html { render :edit, status: :unprocessable_entity }
        # last_list = @list.find(params[:id])
        # debugger
        format.json { render json: { error: @list.errors, name: last_list.name, status: :unprocessable_entity } }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update

    positions = []
    i = 0
    List.where(board_id: @list.board_id).rank(:row_order).each do |list|
      positions[i]=[list.row_order, i+1]
      i=i+1      
    end
    @positions = positions
    
    pos_current = 0;
    pos_new = 0;
    pos_new_more = 0;

    r_order_new = -1;
    r_order_current = -1;
    r_order_new_more = -1;

    # debugger
    
    # Get current position number & current row order
    pos_current = @positions.find { |el| el[0].to_s == @list.row_order.to_s }[1] if @list 
    r_order_current = @positions.find { |el| el[0].to_s == @list.row_order.to_s }[0] if @list 

    # Get the row order selected new position
    if @positions.find { |el| el[0].to_s == params[:list][:row_order] }[1]      
      pos_new = @positions.find { |el| el[0].to_s == params[:list][:row_order] }[1]      
      r_order_new = @positions.find { |el| el[0].to_s == params[:list][:row_order] }[0]      
    end     
    
    pos_current = 0 if pos_current == nil
    
    # If the new position is greater then the old position, but not the last position
    if (pos_new > pos_current) && (pos_new < @positions.length)
      pos_new_more = pos_new + 1 
      r_order_new_more = @positions.find { |el| el[1] == pos_new_more }[0]

      min_l = r_order_new + 1
      max_l = r_order_new_more - 1
      params[:list][:row_order] = (rand(min_l..max_l)).to_s 

    # If the new position is greater then the old position and the last position
    elsif (pos_new > pos_current) && (pos_new == @positions.length)      
      r_order_new_more = r_order_new + 1

      min_l = r_order_new + 1
      max_l = r_order_new_more - 1
      params[:list][:row_order] = (rand(min_l..max_l)).to_s 
    end

    # If we've choose smaller position than the current
    params[:list][:row_order] = (r_order_new - 1).to_s if pos_new < pos_current

    # debugger
    

    respond_to do |format|      

      if @list.update(list_params)

        # debugger

        @update_list = dom_id(@list, :sortable)
        @board = Board.find(@list.board_id)

        format.turbo_stream { render "update_lists", 
          locals: { board: @board, list: @list, position: pos_new }
        }

        # format.turbo_stream { render "update_list", 
        #   locals: { list: @list, update_list: @update_list  }
        # }

        format.html { redirect_to "/boards/#{@list.board_id}", notice: "List was successfully updated." }
        # format.json { render :show, status: :ok, location: @list }
        format.json { render json: { status: 'ok', name: @list.name } }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy
    @update_list = dom_id(@list, :sortable)

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@update_list) }
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
      rescue ActiveRecord::RecordNotFound        
        redirect_to tenants_path
        flash[:danger] = "This List with id = #{params[:id]} doesnt exsists!"
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name, :row_order, :positions)
    end
end

app/views/lists/_form.html.erb
<%= form_with(model: list, class: "contents") do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/lists/_form_edit.html.erb
<%# <%= @positions %>
<br>
<%= form_with(model: list, class: "contents") do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>




  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%#= form.label :positions %>    
    <%= form.select :row_order, @positions.map{|el| [el[1], el[0]] }, {prompt: "Select position", :selected => @list.row_order} %>
  </div>

      <%# <div data-controller="language"> %>
      <%#= select_tag(:language_scan, options_for_select([['eng', 1],'deu', 2],'fra', 3]], 1), data: {action: "change->language#change"}, class:'form-select') %>
      <%#= form.select :voice_language, ["eng", "deu", "fra", "ita", "swe", "ita", "ukr", "spa"], {prompt: "Select a language", :selected => post.voice_language}, {class:'form-select', data: {action: "change->language#change"} } %>
      <%#= form.select :positions, voice_langs, {prompt: "Select a language", :selected => post.voice_language}, {class:'form-select', data: {action: "change->voice-input#change"}} %>
    <%# </div> %>

  <div class="my-5">
    <%#= form.label :board_id %>
    <%#= form.text_field :board_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/lists/_form_new.html.erb
<%#= form_with(model: list, class: "contents") do |form| %>
<%= form_with url: board_lists_path do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%#= form.label :board_id %>
    <%#= form.text_field :board_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>" class="bg-white pt-0 pb-4 shadow-xl ring-2 ring-gray-900/5 mx-auto max-w-lg rounded-lg px-3 overflow-y-auto max-h-[calc(100vh-150px)]" 
style ="background-color:#f8f8f8">
  <p class="my-5">
    <strong class="block font-medium mb-1 cursor-pointer"><%#= list.id %> 
    </strong>
    <div data-controller="list" data-list-id="<%= list.id %>" data-action="click->list#handleClick">
      <div data-list-target="name" class="p-2 rounded-lg task_style_list">
        <%= link_to list.name, '' %>
      </div>    
    </div>
    
    
    <%#= list.row_order %>

  </p>
  <%#= link_to "New task", new_list_task_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>

      <div id="tasks_add_new_<%= list.id %>" data-controller="sortable" data-sortable-group-value="tasks" data-sortable-list-id="<%= list.id %>" class="list-decimal px-0">
      <% list.tasks.rank(:row_order).each do |task| %>
        <div data-sortable-update-url="<%= sort_task_path(task) %>" 
        id="sortable_task_<%= task.id %>"
         >
            <%= render task %>
        </div>
      <% end %>
    </div>


    
    
    <div data-controller="task"  data-list-id="<%= list.id %>" style="min-height:42px; margin:0px; position: relative">
      <div data-action="click->task#handleAddNewTask" class="task_style_list">
        <div data-task-target="addTName">
          <%= link_to "+ Add task", '', class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>   
        </div>
      </div>
    </div>

    <%= link_to "Edit this list", edit_list_path(list), data: {turbo_frame: "modal"}, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Destroy", list_path(list),  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    
    
    <%#= link_to "+ Add task", "/lists/#{list.id}/tasks/new", data: {turbo_frame: "modal"}, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    
    <!-- <div class="inline-block ml-2">
      <%#= button_to "Destroy", edit_list_path(list), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div> -->
  <% if action_name != "show" %>

  <!-- data: {turbo_frame: "modal", action:"click->turbomodal#blurMe"} -->
    <%#= link_to "Show this list", list, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <!-- <hr class="mt-6"> -->
  <% end %>
</div>

app/views/lists/_update_list.html.erb
      <%# <% @lists.each do |list| %>
        <!-- <li data-sortable-id="<%= list.id %>"> -->
        
        <div data-sortable-update-url="<%= sort_list_path(list.id) %>" id="sortable_list_<%= list.id%>" style="min-width:300px" class="px-4 pl-0 ">
          <%= render list %>
          
        </div>
      <%# <% end %> 

app/views/lists/_update_lists.html.erb
  <div data-controller="turboload" data-list-updated ="<%= list_updated.id %>" data-turboload-target="turboload" id="lists" class="min-w-full flex flex flex-col md:flex-row overflow-y-hidden overflow-x-auto" style="display: flex; flex-direction: column; flex: 1 1 0%; overflow-y: hidden; overflow-x: auto;">
    <div id="lists-sortable" class="list-disc" data-controller="sortable" style="display: flex;">
      <% board.lists.rank(:row_order).each do |list| %>
          <div data-sortable-update-url="<%= sort_list_path(list.id) %>" id="sortable_list_<%= list.id%>" class="p-2 list_width" >
            <%= render list %>
          </div>

      <% end %>
    </div>
  </div>

app/views/lists/edit.html.erb
 <%#= turbo_frame_tag "modal" do %>
<%= turbo_frame_tag :modal do %>
  <div data-controller="turbomodal" data-action="turbo:submit-end->turbomodal#submitEnd">
    <div class="modal">
        <div class="mx-auto md:w-2/3 w-full">

        <div data-controller="turbomodal" data-action="click->turbomodal#close">
            <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
                <svg class="fill-current h-6 w-6 text-black" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
            </span>
        </div>
          <h1 class="font-bold text-4xl">Editing list</h1>

          <%= render "form_edit", list: @list %>

          <%#= link_to "Cancel","#", data:{ controller: "turbomodal", action: "click->turbomodal#close" }, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

          <%#= link_to "Show this list", @list, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
          <%#= link_to "Back to lists", lists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
        </div>
    </div>
  </div> 
  <div class="blur-overlay"></div>
<% end %>

app/views/lists/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Lists</h1>
    <%= link_to "New list", new_board_list_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div> 

  <!-- /lists/${event.item.dataset.sortableId}/sort?id=${event.item.dataset.sortableId}&row_oder_position=${event.newIndex} -->

  <div id="lists" class="min-w-full flex">
    <div class="list-disc" data-controller="sortable" style="display: flex">
      <% @lists.each do |list| %>
        <!-- <li data-sortable-id="<%= list.id %>"> -->
        <div data-sortable-update-url="<%= sort_list_path(list.id) %>" id="sortable_list_<%= list.id%>" style="min-width:300px">
          <%= render list %>
        </div>
      <% end %>
    </div>


    <%#= render @lists %>


  </div>
</div>

app/views/lists/new.html.erb
<%= turbo_frame_tag :modal do %>
  <div data-controller="turbomodal" data-action="turbo:submit-end->turbomodal#submitEnd">
    <div class="modal">
      <div class="mx-auto md:w-2/3 w-full">
        
        <div data-controller="turbomodal" data-action="click->turbomodal#close">
            <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
                <svg class="fill-current h-6 w-6 text-black" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
            </span>
        </div>

        <h1 class="font-bold text-4xl">New list</h1>

        <%= render "form_new", list: @list %>

        <%#= link_to "Back to lists", board_lists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </div>
    </div>
  </div>
  <div class="blur-overlay"></div>
<% end %>

app/views/lists/prepend_list.turbo_stream.erb
<!-- we can target with the div id="posts" on the index page --> 
<%#= update_list%>
<%= turbo_stream.prepend "lists-sortable" do %>
    <%= render partial: "update_list", locals: { list: @list } %>
    <%#= render @list %>  
<% end %>
<!-- we replace the new.html.erb  --> 
<%#= turbo_stream.replace "new_post", partial: "form", locals: { post: Post.new} %>

app/views/lists/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @list %>

    <%= link_to "Edit this list", edit_list_path(@list), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this list", list_path(@list), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%#= link_to "Back to lists", board_lists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/lists/update_list.turbo_stream.erb
<!-- we can target with the div id="posts" on the index page --> 
<%#= update_list%>
<%= turbo_stream.update list_2_update do %>
    <%= render partial: "lists/update_list", locals: { board: board, list: list} %>
    <%#= render @list %>  
<% end %>
<!-- we replace the new.html.erb  --> 
<%#= turbo_stream.replace "new_post", partial: "form", locals: { post: Post.new} %>

app/views/lists/update_lists.turbo_stream.erb
<!-- we can target with the div id="posts" on the index page --> 
<%#= update_list%>

<!-- Update the "lists" + shift the y-scroll to the new position --> 
<%= turbo_stream.replace "lists" do %>
    <%= render partial: "lists/update_lists", locals: { board: board, list_updated: list} %>
    <%#= render @list %>  
<% end %>