config/routes.rb
Rails.application.routes.draw do

  resources :tenants do
    resources :boards, only: [:index, :new, :create]

    resources :boards do
      collection do
        get :select_all
      end
    end 

    resources :members do
      collection do # invite_tenant_members POST /tenants/:tenant_id/members/invite(.:format) members#invite
        post :invite # Invite a member to the current tenant
        get :select_all
      end
    end
  end

  resources :boards, only: [:show, :edit, :update, :destroy]

  resources :boards, only: [:show] do
    resources :lists, only: [:index, :new, :create]  
  end

  # DEFINE ROUTES FOR :tasks, :lists, :sort  (:show, :edit, :update, :destroy)

  resources :lists, only: [:show] do
    resources :tasks, only: [:index, :new, :create]  
  end

  resources :lists, only: [:show, :edit, :update, :destroy] do
    member do # sort_list PUT /lists/:id/sort(.:format) lists#sort
      put :sort
      patch :update_name
    end
  end 

  resources :tasks, only: [:show, :edit, :update, :destroy] do
    member do # sort_task PUT /tasks/:id/sort(.:format) tasks#sort
      put :sort
    end
  end

  resources :tasks do
    resource :cover_image, only: [:destroy], module: :tasks
  end

# SEARCH TASKS
# get 'search_friend', to: 'users#search'



  # resources :tasks do
  #   member do # sort_task PUT /tasks/:id/sort(.:format) tasks#sort
  #     put :sort
  #   end
  # end


  # collection do - sort_lists 
  # member do - sort list


  # collection do - invite_tenant_members 
  # member do - invite_tenant_member


  # resources :blog_posts do
  #   resource :cover_image, only: [:destroy], module: :blog_posts
  # end

  # get "/tenants/:tenant_id/boards", to: "boards#index", as: "boards"
  #post "/tenants/:tenant_id/boards", to: "boards#create", as: "boards"

  # post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"

  # devise_for :users
  # devise_for :users, :controllers => { :invitations => 'invitations' }


    devise_for :users, controllers: {
      registrations: "users/registrations"
    }

  put 'boards/users/sidebar_position', to: "preferences#sidebar_position"
  # get 'boards/users/sidebar_position', to: "preferences#get"
  root 'static_pages#landing_page'
  get 'dashboard', to: 'static_pages#dashboard'

  get 'selected_board', to: 'tasks#selected_board'

  get 'selected_list', to: 'tasks#selected_list'

  # PDF
  get 'tasks/pdf/:id', to: 'tasks#pdf', as: 'task_pdf'
  
  get "download_pdf", to: "tasks#pdf_download"
  get "preview_pdf", to: "tasks#pdf_preview"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/tenant_headers/_tenant_content.html.erb
                  <div class="justify-between items-center flex flex-wrap w-full py-1" 
                  <%# style="border: 1px solid red" %>
                  >
                      <div class="flex lg:w-1/2 mb-2 lg:mb-0  items-center">

                        <div class="items-center px-2"><h6 class="text-md font-bold ">
                        <%#= tenant.name %>
                        <%#= link_to tenant.name, tenant_path(tenant.id)%>
                        Boards              
                        </h6>
                          <%#= link_to "New Workspace", new_tenant_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>              
                          <%#= link_to "New list", "/boards/#{@board.id}/lists/new", data: {turbo_frame: "modal"}, class: "space-x-2 rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium;" %>
                        </div>
                    
                      </div>
                      <div class="flex lg:w-1/2 mb-2 lg:mb-0">
                        <div class="px-1">
                        <%#= link_to "Boards", select_all_tenant_boards_path(@current_tenant_id), data:{turbo_stream: true} %>
                        <%= link_to tenant_path(tenant.id), data:{turbo_stream: true}, class: "px-2 py-1 text-xs font-medium text-center inline-flex items-center text-white bg-gray-600 rounded-sm hover:bg-gray-600 focus:ring-2 focus:outline-none focus:ring-blue-300 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-blue-800" do %>
                        <i class="fa-brands fa-flipboard mr-1"></i>   
                        <%#= link_to "Boards", tenant_boards_path(tenant.id)%>                     
                        Boards
                        <% end %>                      
                        </div>
                        <div class="px-1">
                        <%= link_to select_all_tenant_members_path(tenant.id), data:{turbo_stream: true}, class: "px-2 py-1 text-xs font-medium text-center inline-flex items-center text-white bg-gray-400 rounded-sm hover:bg-gray-600 focus:ring-2 focus:outline-none focus:ring-blue-300 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-blue-800", style:"background-color:#62d092" do %>
                        <i class="fa-solid fa-people-group mr-1"></i>Members
                        <% end %>                          
                        </div>

                        <div class="px-1">
                        <%= link_to new_tenant_board_path(tenant.id), data: {turbo_frame: "modal"}, class: "px-2 py-1 text-xs font-medium text-center inline-flex items-center text-white bg-blue-500 rounded-sm hover:bg-blue-600 focus:ring-2 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
                        <i class="fa-solid fa-square-plus mr-1"></i>New Board
                        <% end %>                          
                        </div>
                      </div>
                  </div>

                    
                    <div id="tenant_<%= tenant.id %>" class="flex flex-wrap px-0" >
                    <% tenant.boards.each do |board| %>

                    <%#= board.name %>
                    
                      <%= render partial: "layouts/board_thumbnails/board_thumbnail", 
                      locals: { board: board, members: tenant.members, tenant: tenant } %>

                    <% end %>
                    </div>

app/views/layouts/tenant_headers/_tenant_header.html.erb
                  <div class="justify-between items-center flex flex-wrap w-full py-1" 
                  <%# style="border: 1px solid red" %>
                  >
                      <div class="flex lg:w-1/2 mb-2 lg:mb-0  items-center">
                        <!-- <div class="avatar_circle" style="color:white; padding: 4px 12px 4px 12px">
                            <%#= tenant.name.to_s[0].upcase %>
                        </div> -->
                        <div class="items-center px-2"><h6 class="text-md font-bold ">
                        <%#= tenant.name %>
                        <%= link_to tenant.name, tenant_path(tenant.id)%>              
                        </h6>
                          <%#= link_to "New Workspace", new_tenant_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>              
                          <%#= link_to "New list", "/boards/#{@board.id}/lists/new", data: {turbo_frame: "modal"}, class: "space-x-2 rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium;" %>
                        </div>
                    
                      </div>
                      <div class="flex lg:w-1/2 mb-2 lg:mb-0">
                        <div class="px-1">
                        <%#= link_to "Boards", select_all_tenant_boards_path(@current_tenant_id), data:{turbo_stream: true} %>
                        <%= link_to tenant_path(tenant.id), class: "px-2 py-1 text-xs font-medium text-center inline-flex items-center text-white bg-gray-600 rounded-sm hover:bg-gray-600 focus:ring-2 focus:outline-none focus:ring-blue-300 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-blue-800" do %>
                        <%#= link_to select_all_tenant_boards_path(tenant.id), data:{turbo_stream: true}, class: "px-2 py-1 text-xs font-medium text-center inline-flex items-center text-white bg-gray-600 rounded-sm hover:bg-gray-600 focus:ring-2 focus:outline-none focus:ring-blue-300 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-blue-800" do %>
                        <i class="fa-brands fa-flipboard mr-1"></i>   
                        <%#= link_to "Boards", tenant_boards_path(tenant.id)%>                     
                        Boards
                        <% end %>                      
                        </div>
                        <div class="px-1">
                        <%= link_to select_all_tenant_members_path(tenant.id), data:{turbo_stream: true}, class: "px-2 py-1 text-xs font-medium text-center inline-flex items-center text-white bg-gray-400 rounded-sm hover:bg-gray-600 focus:ring-2 focus:outline-none focus:ring-blue-300 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-blue-800", style:"background-color:#62d092" do %>
                        <i class="fa-solid fa-people-group mr-1"></i>Members
                        <% end %>                          
                        </div>

                        <div class="px-1">
                        <%= link_to new_tenant_board_path(tenant.id), data: {turbo_frame: "modal"}, class: "px-2 py-1 text-xs font-medium text-center inline-flex items-center text-white bg-blue-500 rounded-sm hover:bg-blue-600 focus:ring-2 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
                        <i class="fa-solid fa-square-plus mr-1"></i>New Board
                        <% end %>                          
                        </div>
                      </div>
                  </div>

                    
                    <div id="tenant_<%= tenant.id %>" class="flex flex-wrap px-0" >
                    <% tenant.boards.each do |board| %>

                    <%#= board.name %>
                    
                      <%= render partial: "layouts/board_thumbnails/board_thumbnail", 
                      locals: { board: board, members: tenant.members, tenant: tenant } %>

                    <% end %>
                    </div>