config/routes.rb
Rails.application.routes.draw do

  resources :tenants do
    resources :boards, only: [:index, :new, :create]

    resources :boards do
      collection do
        get :select_all
      end
    end 

    resources :members do
      collection do # invite_tenant_members POST /tenants/:tenant_id/members/invite(.:format) members#invite
        post :invite # Invite a member to the current tenant
        get :select_all
      end
    end
  end

  resources :boards, only: [:show, :edit, :update, :destroy]

  resources :boards, only: [:show] do
    resources :lists, only: [:index, :new, :create]  
  end

  # DEFINE ROUTES FOR :tasks, :lists, :sort  (:show, :edit, :update, :destroy)

  resources :lists, only: [:show] do
    resources :tasks, only: [:index, :new, :create]  
  end

  resources :lists, only: [:show, :edit, :update, :destroy] do
    member do # sort_list PUT /lists/:id/sort(.:format) lists#sort
      put :sort
      patch :update_name
    end
  end 

  resources :tasks, only: [:show, :edit, :update, :destroy] do
    member do # sort_task PUT /tasks/:id/sort(.:format) tasks#sort
      put :sort
    end
  end

  resources :tasks do
    resource :cover_image, only: [:destroy], module: :tasks
  end

# SEARCH TASKS
# get 'search_friend', to: 'users#search'



  # resources :tasks do
  #   member do # sort_task PUT /tasks/:id/sort(.:format) tasks#sort
  #     put :sort
  #   end
  # end


  # collection do - sort_lists 
  # member do - sort list


  # collection do - invite_tenant_members 
  # member do - invite_tenant_member


  # resources :blog_posts do
  #   resource :cover_image, only: [:destroy], module: :blog_posts
  # end

  # get "/tenants/:tenant_id/boards", to: "boards#index", as: "boards"
  #post "/tenants/:tenant_id/boards", to: "boards#create", as: "boards"

  # post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"

  # devise_for :users
  # devise_for :users, :controllers => { :invitations => 'invitations' }


    devise_for :users, controllers: {
      registrations: "users/registrations"
    }

  put 'boards/users/sidebar_position', to: "preferences#sidebar_position"
  # get 'boards/users/sidebar_position', to: "preferences#get"
  root 'static_pages#landing_page'
  get 'dashboard', to: 'static_pages#dashboard'

  get 'selected_board', to: 'tasks#selected_board'

  get 'selected_list', to: 'tasks#selected_list'

  # PDF
  get 'tasks/pdf/:id', to: 'tasks#pdf', as: 'task_pdf'
  
  get "download_pdf", to: "tasks#pdf_download"
  get "preview_pdf", to: "tasks#pdf_preview"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/task.rb
class Task < ApplicationRecord

  # Action text migration
  has_one_attached :cover_image
  has_rich_text :description

  validates :name, presence: true  
  belongs_to :list
  # belongs_to :board

  include RankedModel
  ranks :row_order, with_same: :list_id
end

app/controllers/tasks/cover_images_controller.rb
class Tasks::CoverImagesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_task

    include ActionView::RecordIdentifier # include dom_id method identifier
  
    def destroy

      @task.cover_image.purge_later
      # debugger
      # redirect_to edit_task_path(@task)
      respond_to do |format|
        # format.turbo_stream { render "tasks/cover_image/remove_image", 
        #   locals: {cover_image_id: "cover_image_#{@task.id}" , flash_notice: "Cover image was successfully removed from your data!" }
        # }
 
        format.turbo_stream { render "tasks/cover_image/remove_image", 
               locals: {cover_image_id: "cover_image_task_#{@task.id}", task: @task, flash_notice: "Cover image was successfully removed from your data!" }
            }

        # format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(@task, :cover_image)) }
        format.html {redirect_to edit_task_path(@task) }
    end
    end

    private

    def set_task
        @task = Task.find(params[:task_id]) if user_signed_in? 
        # rescue ActiveRecord::RecordNotFound
        #     redirect_to tasks_path
        #     flash[:danger] = "This Blog Post with id = #{params[:id]} doesnt exsists!"
    end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy pdf]

  include ActionView::RecordIdentifier # include dom_id method identifier

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  def search
    #binding.break
    #render json: params[:friend]
    #binding.break 
    #debugger   

    if !params[:friend].empty?

      # @stock = Stock.new_lookup(params[:stock])
      # strip! - removes empty signs
      @friends = User.find_friends(params[:friend])      
      
      if @friends
          # exclude current user from the friends list
          @friends = current_user.except_current_user(@friends)

              respond_to do |format|
                  format.turbo_stream { render "users/create_friends"}
              end
             
          
      else 
              flash.now[:danger] = "Please enter a valid symbol to search"
              # redirect_to my_data_path
              respond_to do |format|
                  format.turbo_stream { render "users/create_friends"}
              end
              #binding.break
              # render json: @stock
      end
          

    else 
              flash.now[:alert] = "You need to place a symbol!"
              respond_to do |format|
                  format.turbo_stream { render "users/create_friends"}
              end
    end
              # redirect_to my_data_path

  end

  def sort
    @task = Task.find(params[:id])
    # debugger
    respond_to do |format|
      if @task.update(row_order_position: params[:row_order_position], list_id: params[:list_id])

        format.html {
          # headers["www-Authenticate"] = root_url
          # head :unauthorized
          head :no_content
        }
        # format.turbo_stream{ head :no_content }    
        
        @update_task = dom_id(@task, :sortable)
        # debugger
        #format.turbo_stream { render turbo_stream: turbo_stream.update(dom_id(@list, :sortable))}
        format.turbo_stream { render "update_task", 
          locals: { task: @task, update_task: @update_task  }
        }

      end
    end
  end

  def selected_list
      # GET THE POSITIONS IN THE CURRENT LIST

      @selected_list = List.find(params[:selected_list])
      positions = []
      i = 0      

      Task.where(list_id: @selected_list.id).rank(:row_order).each do |task|
        positions[i]=[i+1, task.row_order]
        i=i+1      
      end
      @positions = positions
      @target = params[:target]

      # debugger

      # if Task.find(params[:id]).present
      #   @task = Task.find(params[:id]) 
      # else 
      #   @task = Task.new(name: params[:name], list_id: params[:list_id], row_order: (@positions[i][1].to_i+1).to_s)
      # end

      respond_to do |format|

        format.turbo_stream 
        # format.turbo_stream { render "update_task", 
        #   locals: { task: @task, update_task: @update_task  }
        # }
        # format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
        # format.json { head :no_content }
      end
  end

  def selected_board
    @selected_board = Board.find(params[:selected_board])
    selected_board_lists = []
    i = 0
    List.where(board_id: params[:selected_board]).rank(:row_order).each do |list|
      selected_board_lists[i]=[list.name, list.id]
      i=i+1      
    end

    @selected_board_lists = selected_board_lists

    positions = []
    i = 0      
    if @selected_board_lists.length != 0
    
      Task.where(list_id: @selected_board_lists[0][1]).rank(:row_order).each do |task|
        positions[i]=[i+1, task.row_order]
        i=i+1      
      end
    else # @selected_board_lists = [["No Lists",0]]
    end
    @positions = positions

     @positions = [] if @positions.length == 0


    @target = params[:target]
    @tasks_target = params[:tasks_target]
    
    respond_to do |format|

      format.turbo_stream 
      # format.turbo_stream { render "update_task", 
      #   locals: { task: @task, update_task: @update_task  }
      # }
      # format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      # format.json { head :no_content }
    end


  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  # GET the lists, to which belongs the current task
    selected_board_lists = []
    list_boards = []
    i = 0
    @cur_list = List.find(@task.list_id)
    @cur_board_id = @cur_list.board_id
    @cur_tenant_id = Board.find(@cur_board_id).tenant_id

    List.where(board_id: @cur_board_id).rank(:row_order).each do |list|
      selected_board_lists[i]=[list.id, list.name]
      i=i+1      
    end

    @selected_board_lists = selected_board_lists

    # Get the boards, which are belogs to the current tenant
    i = 0    
    Board.where(tenant_id: @cur_tenant_id).each do |board|
      list_boards[i]=[board.id, board.name]
      i=i+1      
    end

    @list_boards = list_boards

    # GET THE POSITIONS IN THE CURRENT LIST
    positions = []
    i = 0
    Task.where(list_id: @task.list_id).rank(:row_order).each do |list|
      positions[i]=[list.row_order, i+1]
      i=i+1      
    end
    @positions = positions

    # debugger

  end

  # POST /tasks or /tasks.json
  def create

    @task = Task.new(name: params[:name], list_id: params[:list_id], description: params[:description], 
      cover_image: params[:cover_image] )

    # debugger

    respond_to do |format|
      if @task.save
        board = List.find(params[:list_id]).board_id

        tasks_add_new = "tasks_add_new_#{params[:list_id]}"

        # format.turbo_stream { render "prepend_task", 
        #   locals: { tasks_add_new: tasks_add_new, task: @task }
        # }

        @list_2_update = "sortable_list_#{ @task.list_id }"

        @list = List.find(@task.list_id)
        @board = Board.find(@list.board_id)

        format.turbo_stream { render "lists/update_list", 
          locals: { board: @board, list: @list, list_2_update: @list_2_update, position: 0  }
        }

        format.html { redirect_to "/boards/#{board}", notice: "Task was successfully created." }
        format.json { render json: { status: 'ok', name: @task.name, task_id: @task.id } }
        # format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update    

    # GET THE POSITIONS IN THE CURRENT LIST
    positions = []
    i = 0
    Task.where(list_id: params[:task][:list_id].present? ? params[:task][:list_id] : @task.list_id).rank(:row_order).each do |task|
      positions[i]=[task.row_order, i+1]
      i=i+1      
    end
    @positions = positions

    pos_current = nil;
    pos_new = 0;
    pos_new_more = 0;

    r_order_new = nil;
    r_order_current = nil;
    r_order_new_more = nil;
    
    # CASE 1: Same board, same list change the task position in the same list. 
    # Array @positions includes the current & the new row_orders
    # Check if it is the same boards
    # Check if it is the same lists
    cur_list_id = @task.list_id
    cur_board_id = List.find(@task.list_id).board_id

    new_list_id = params[:task][:list_id].to_i if params[:task][:list_id].present?
    new_board_id = params[:task][:board_id].to_i if params[:task][:board_id].present?

    # debugger

    if cur_board_id == new_board_id

      # CASE 1: Same board, same list change the task position in the same list.
      if cur_list_id == new_list_id

        pos_current = @positions.find { |el| el[0].to_s == @task.row_order.to_s}[1] if @task 
        r_order_current = @task.row_order 
        
        pos_new = @positions.find { |el| el[0].to_s == params[:task][:row_order] }[1]      
        r_order_new = @positions.find { |el| el[0].to_s == params[:task][:row_order] }[0]

        

        # If the new position is greater then the old position, but not the last position
        if pos_current && pos_new > pos_current && pos_new < @positions.length
          pos_new_more = pos_new + 1 
          
          r_order_new_more = @positions.find { |el| el[1] == pos_new_more }[0]

          min_l = r_order_new
          max_l = r_order_new_more

          # min_l = min_l -1 if min_l < 0
          # max_l = max_l -1 if max_l < 0

          # params[:task][:row_order] = rand(min_l..max_l).to_s

          params[:task][:row_order] = max_l.to_s

        # If the new position is greater then the old position and the last position
        elsif (pos_new > pos_current) && (pos_new == @positions.length)      
          r_order_new_more = r_order_new + 1
          min_l = r_order_new +1
          max_l = r_order_new_more + 1
          params[:task][:row_order] = (rand(min_l..max_l)).to_s 
        
        # If we've choose smaller position than the current
        elsif (pos_new < pos_current)

          # debugger
          params[:task][:row_order] = (r_order_new).to_s
        end
        params[:task][:row_order] = 0 if !pos_current && @positions.length == 0       
      
      # CASE 2: Same board, different lists
      else
        pos_2paste = @positions.find { |el| el[0].to_s == params[:task][:row_order].to_s}[1] if params[:task][:row_order].present?
        r_order_2paste = @positions.find { |el| el[0].to_s == params[:task][:row_order]}[0] if params[:task][:row_order].present?

        # if it is the first position to paste
        params[:task][:row_order] = r_order_2paste -1 if pos_2paste == 1

        #if it is the last position to paste
      #if it is the last position to paste
      params[:task][:row_order] = r_order_2paste +1 if params[:task][:row_order].present? && pos_2paste == @positions.length && @positions.length != 1
        
        # If it is the middle position. 

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: "contents") do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :list_id %>
    <%= form.text_field :list_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/tasks/_form_edit.html.erb
<%#= @positions %>
<%# , data: {turbo_frame: "_top"} %>
<%= form_with(model: task, class: "contents") do |form| %>
<%#= form_with url: list_tasks_path do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
        <%= form.label :cover_image %>
          <% if task.cover_image.present?%>

            <div id="<%= dom_id(task, :cover_image) %>">          
              <%= image_tag task.cover_image, class:"w-1/3" %>
              <%= link_to "Delete Cover Image", task_cover_image_path(task), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are You sure?"}, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
            </div>
          <%end%>
        <%= form.file_field :cover_image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

    <p class="my-5">
      <%= link_to "VIEW PDF", task_pdf_path(task), target: :_blank %>
    </p>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, rows: 7, 
    class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full",
    style:"resize: vertical; min-height: 200px" %>
  </div>

  <div data-controller="task">
    <div class="my-5" >
      <%= form.label :board_id %>      
        <%= form.select :board_id, @list_boards.map{|el| [el[1], el[0]] }, {prompt: "Select position", :selected => @cur_board_id}, {class:'form-select', data: {action: "change->task#changeBoard"} } %>
    </div>

    <div class="my-5" >
      <%= form.label :list_id %>          
        <%= form.select :list_id, @selected_board_lists.map{|el| [el[1], el[0]] }, {prompt: "Select position", :selected => @task.list_id}, {class:'form-select', data: { task_target: "listsSelect", action: "change->task#changeList"} } %>
      
    </div>

    <% if @positions.length > 0 %>
      <div class="my-5" >
        <%= form.label :task_id %>    
        <%= form.select :row_order, @positions.map{|el| [el[1], el[0]] }, {prompt: "Select position", :selected => @task.row_order}, {class:'form-select', data: { task_target: "tasksSelect"} } %>
      </div>
    <% end %> 

    <div class="inline" id="submit_button">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  </div>
<% end %>

app/views/tasks/_form_new.html.erb
<%#= form_with(model: task, class: "contents") do |form| %>
<%= form_with url: list_tasks_path do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
        <%= form.label :cover_image %>
          <% if task.cover_image.present?%>

            <div id="<%= dom_id(task, :cover_image) %>">          
              <%= image_tag task.cover_image, class:"w-1/3" %>
            </div>
            <%= link_to "Delete Cover Image", task_cover_image_path(task), method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are You sure?"}, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
          <%end%>
        <%= form.file_field :cover_image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>


  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%#= form.label :list_id %>
    <%#= form.text_field :list_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>" class="my-3">

    <% if task.cover_image.present?%> 
    <div id="<%= dom_id(task, :cover_image) %>">                     
      <%= image_tag task.cover_image %> 
    </div>           
    <%end%>

    <%# if task.description.body.present?%> 
      <!-- <div id="<%= dom_id(task, :cover_image) %>">                     
        <%= task.description.body %> 
      </div>           -->
    <%#end%>


    <div data-controller="task" data-task-id="<%= task.id %>" 
      class="group hover:hover:bg-slate-100 group hover: rounded-lg" style="min-height:42px; width:242px; margin:0px; position: relative">
        <div data-task-target="tname" class="p-2 border-2 border-gray-200 rounded-lg task_style">
          <%= link_to task.name, "/tasks/#{task.id}/edit", data: {turbo_frame: "modal"}, class:"break-all" %>
        </div>


        <div id="icon_edit" data-action="click->task#handleTaskClick" class="cursor-pointer invisible group-hover:visible edit_task_hover">
          <i class="fa-solid fa-pen fa-xs" style="color: #000000;"></i>
        </div>
    </div>   


  <% if action_name != "show" %>
    <%#= link_to "Show this task", task, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%#= link_to "Edit task", edit_task_path(task), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <!-- <hr class="mt-6"> -->
  <% end %>
</div>

app/views/tasks/_update_task.html.erb
      <%# <% @lists.each do |list| %>
        <!-- <li data-sortable-id="<%= list.id %>"> -->

        <%#= render task %>  
        <div data-sortable-update-url="<%= sort_task_path(task) %>" id="sortable_task_<%= task.id%>" style="min-width:300px">
          <%= render task %>          
        </div>
      <%# <% end %> 

app/views/tasks/edit.html.erb
<%= turbo_frame_tag :modal do %>
  <div class="overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
    <div class="relative p-4 w-full max-w-2xl max-h-full modal" data-controller="turbomodal" data-action="turbo:submit-end->turbomodal#submitEnd">
      <div style="overflow-y: auto;">
        <div class="mx-auto md:w-2/3 w-full">
            <div data-controller="turbomodal" data-action="click->turbomodal#close">
              <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
                  <svg class="fill-current h-6 w-6 text-black" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
              </span>
            </div>
            <h1 class="font-bold text-4xl">Editing task</h1>

            <%= render "form_edit", task: @task %>

            <%#= link_to "Show this task", @task, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
            <%= button_to "Destroy", task_path(@task), method: :delete,  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
            <%#= link_to "Back to tasks", tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
          </div>
        </div>

    </div>
  
    <div class="blur-overlay"></div>
  </div>

<% end %>

app/views/tasks/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Tasks</h1>
    <%= link_to "New task", new_task_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="tasks" class="min-w-full">
    <%= render @tasks %>
  </div>
</div>

app/views/tasks/new.html.erb
<%= turbo_frame_tag :modal do %>
  <div data-controller="turbomodal" data-action="turbo:submit-end->turbomodal#submitEnd">
    <div class="modal">
      <div class="mx-auto md:w-2/3 w-full">

        <div data-controller="turbomodal" data-action="click->turbomodal#close">
            <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
                <svg class="fill-current h-6 w-6 text-black" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
            </span>
        </div>

        <h1 class="font-bold text-4xl">New task</h1>

        <%= render "form_new", task: @task %>

        <%#= link_to "Back to tasks", tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </div>
    </div>
  </div>
  <div class="blur-overlay"></div>
<% end %>

app/views/tasks/prepend_task.turbo_stream.erb
<!-- we can target with the div id="posts" on the index page --> 
<%#= update_list%>
<!--  sortable_list_12 -->

<%= turbo_stream.prepend tasks_add_new do %>
<%#= update_task %>
<%= render task %>  
    <%#= render partial: "update_task", locals: { task: @task } %>
<% end %>


<%#= turbo_stream.prepend "lists-sortable" do %>
    <%#= render partial: "update_list", locals: { list: @list } %>    
<%# end %>
<!-- we replace the new.html.erb  --> 
<%#= turbo_stream.replace "new_post", partial: "form", locals: { post: Post.new} %>

app/views/tasks/selected_board.turbo_stream.erb
<%= turbo_stream.update @target do %>
<%= options_for_select @selected_board_lists %>
<% end %>

<%= turbo_stream.update @tasks_target do %>
<%= options_for_select @positions %>
<% end %>

<%= turbo_stream.update "submit_button" do %>
<%#=  @selected_board_lists.present? %>
    <% if @selected_board_lists.present? %>
        <input type="submit" name="commit" value="Update Task" class="rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" data-disable-with="Update Task">
    <% else %>
        <input type="submit" name="commit" value="Update Task" class="mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" data-disable-with="Update Task" disabled>
    <% end %>
<% end %>

app/views/tasks/selected_list.turbo_stream.erb
<%= turbo_stream.update @target do %>
<%= options_for_select @positions %>
<% end %>

app/views/tasks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @task %>

    <%= link_to "Edit this task", edit_task_path(@task), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this task", task_path(@task), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%#= link_to "Back to tasks", tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/tasks/update_task.turbo_stram.erb
<!-- we can target with the div id="posts" on the index page --> 
<%= turbo_stream.update update_task do %>
    <%= render partial: "update_task", locals: { task: @task } %>
<% end %>
<!-- we replace the new.html.erb  --> 
<%#= turbo_stream.replace "new_post", partial: "form", locals: { post: Post.new} %>

app/views/tasks/update_task.turbo_stream.erb
<!-- we can target with the div id="posts" on the index page --> 

<%= turbo_stream.update update_task do %>
<%#= update_task %>
<%= render task %>  
    <%#= render partial: "update_task", locals: { task: @task } %>
<% end %>
<!-- we replace the new.html.erb  --> 
<%#= turbo_stream.replace "new_post", partial: "form", locals: { post: Post.new} %>