config/routes.rb
Rails.application.routes.draw do

  resources :tenants do
    resources :boards, only: [:index, :new, :create]

    resources :boards do
      collection do
        get :select_all
      end
    end 

    resources :members do
      collection do # invite_tenant_members POST /tenants/:tenant_id/members/invite(.:format) members#invite
        post :invite # Invite a member to the current tenant
        get :select_all
      end
    end
  end

  resources :boards, only: [:show, :edit, :update, :destroy]

  resources :boards, only: [:show] do
    resources :lists, only: [:index, :new, :create]  
  end

  # DEFINE ROUTES FOR :tasks, :lists, :sort  (:show, :edit, :update, :destroy)

  resources :lists, only: [:show] do
    resources :tasks, only: [:index, :new, :create]  
  end

  resources :lists, only: [:show, :edit, :update, :destroy] do
    member do # sort_list PUT /lists/:id/sort(.:format) lists#sort
      put :sort
      patch :update_name
    end
  end 

  resources :tasks, only: [:show, :edit, :update, :destroy] do
    member do # sort_task PUT /tasks/:id/sort(.:format) tasks#sort
      put :sort
    end
  end

  resources :tasks do
    resource :cover_image, only: [:destroy], module: :tasks
  end

# SEARCH TASKS
# get 'search_friend', to: 'users#search'



  # resources :tasks do
  #   member do # sort_task PUT /tasks/:id/sort(.:format) tasks#sort
  #     put :sort
  #   end
  # end


  # collection do - sort_lists 
  # member do - sort list


  # collection do - invite_tenant_members 
  # member do - invite_tenant_member


  # resources :blog_posts do
  #   resource :cover_image, only: [:destroy], module: :blog_posts
  # end

  # get "/tenants/:tenant_id/boards", to: "boards#index", as: "boards"
  #post "/tenants/:tenant_id/boards", to: "boards#create", as: "boards"

  # post "products/add_to_cart/:id", to: "products#add_to_cart", as: "add_to_cart"

  # devise_for :users
  # devise_for :users, :controllers => { :invitations => 'invitations' }


    devise_for :users, controllers: {
      registrations: "users/registrations"
    }

  put 'boards/users/sidebar_position', to: "preferences#sidebar_position"
  # get 'boards/users/sidebar_position', to: "preferences#get"
  root 'static_pages#landing_page'
  get 'dashboard', to: 'static_pages#dashboard'

  get 'selected_board', to: 'tasks#selected_board'

  get 'selected_list', to: 'tasks#selected_list'

  # PDF
  get 'tasks/pdf/:id', to: 'tasks#pdf', as: 'task_pdf'
  
  get "download_pdf", to: "tasks#pdf_download"
  get "preview_pdf", to: "tasks#pdf_preview"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :tenant

  has_many :boards, dependent: :destroy
end

app/controllers/members_controller.rb
class MembersController < AuthorizedController
    # after_invitation_accepted :email_invited_by
    #before_action :set_current_tenant, only: [:index, :invite]
    def index
        #@members = Member.find(params[:tenant_id].
        @members = @current_tenant.members


        #respond_to do |format|



        # format.turbo_stream  { render partial: "members", 
        #     locals: { members: @members  }
        #   }

        # end
    end

    def select_all
        #@members = Member.find(params[:tenant_id].
        
        @members = @current_tenant.members

        # debugger 
        respond_to do |format|
            
            format.turbo_stream  { render partial: "members/members_all", 
                locals: { members: @members  }
            }
            # format.html { render :index }

        end
    end



    def invite
        email = params[:email]
        #binding.break
        unless !email.blank?  
            flash[:danger] = "No email is provided!"
            return redirect_to tenant_members_path(@current_tenant)
        end
        # IF USER IS ALREADY EXIST & HAVE NO MEMBERSHIP 
        user_mail = User.find_by(email: email)
        if user_mail.present? && !(User.find_by(email: email).tenants.include?(@current_tenant))
            UserMailer.with(user: user_mail, invited_user: current_user, tenant: @current_tenant, role: "editor").invitation_accepted.deliver_later 
        end

        user = User.find_by(email: email) || User.invite!({email: email}, current_user,  tenant: @current_tenant)

        unless user.valid?  
            flash[:danger] = "Email invalid"
            return redirect_to tenant_members_path(@current_tenant)
        end

        user.members.find_or_create_by(tenant: @current_tenant, roles: {admin:false, editor: true})

        #UserMailer.with(user: @user).welcome_email.deliver_later

        # MemberMailer.with(current_user: current_user, user: user, tenant: @current_tenant, role: "editor").member_created.deliver_later
        # TODO: Email that user has been added to this workspace
        
        flash[:success] = "Member with #{email} is invited!"
        redirect_to tenant_members_path(@current_tenant)

    end

    # private

    # def email_invited_by
    #     flash[:success] = "Member with #{email} has accepted the invitation!"
    # end

    # def authorize_member
    #     unless @tenant.users.include?(current_user)
    #       flash[:danger] = "You are not a member"
    #       return redirect_to root_path
    #     end
    # end

    # def set_current_tenant
    #     @current_tenant = Tenant.find(params[:tenant_id])        
    # end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_member.html.erb
<div id="<%= dom_id member %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= member.user.email %>
    <%= member.roles %>
  </p>

  <% if action_name != "show" %>
    <%#= link_to "Show this member", tenant_member_path(member), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%#= link_to "Edit this member", edit_tenant_member_path(member), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/members/_members_all.turbo_stream.erb
<%= turbo_stream.replace 'turbo_page_update' do %>

  <div id="turbo_page_update" class="w-1/6 md:w-4/6 lg:w-5/6 flex-grow overflow-y-auto max-h-[calc(100vh-80px)]" 
  style="overflow-y: auto;">
      <div class="top-2" >
            <div class="bg-gray-200 p-4 flex justify-between items-center">
              <div id="sidebar_mobile_new_list" class="flex">                
                    <%# <div class="md:hidden" role="button" data-action="click->navbar#toggle" >
                      &#9776;
                    </div> %>
                    <div class="hidden md:flex sm:flex">
                      <%= render partial: "boards/form_search", locals: {} %>
                    </div>
                    <div>
                      <%#= link_to "New list", "/boards/#{@board.id}/lists/new", data: {turbo_frame: "modal"}, class: "space-x-2 rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium;" %>
                    </div>
              </div>
            </div>
        </div>

      <div class="flex flex-row h-[calc(100vh-150px)] md:h-[calc(100vh-146px)] lg:h-[calc(100vh-146px)] p-2">                      

                    <div class="w-full">
                    <% if notice.present? %>
                        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
                    <% end %>

                    <h1>Invite Members</h1>
                    <div class="py-2">
                        <%= form_with url:invite_tenant_members_path do |form| %>
                        <%= form.text_field :email, placeholder: "Email" %>
                        <%= form.submit "Invite", class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %> 
                        <% end %>
                    </div>

                    <div class="flex justify-between items-center">
                        <h1 class="font-bold text-4xl">Members</h1>
                        <%#= link_to "New member", new_tenant_member_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
                    </div>

                    <div id="tenants" class="min-w-full">
                        <%= render @members %>
                    </div>
                    </div>
      </div>
  </div>
 
<% end %>

app/views/members/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1>Invite Members</h1>
  <div class="py-2">
    <%= form_with url:invite_tenant_members_path do |form| %>
      <%= form.text_field :email, placeholder: "Email" %>
      <%= form.submit "Invite", class: "rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %> 
    <% end %>
  </div>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Members</h1>
    <%#= link_to "New member", new_tenant_member_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="tenants" class="min-w-full">
    <%= render @members %>
  </div>
</div>